In [ ]:
import numpy as np

rng = np.random.default_rng(seed=12345)
X1 = rng.uniform(0,1,10)


(array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
        0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287]),
 array([0.24824571, 0.94888115, 0.66723745, 0.09589794, 0.44183967,
        0.88647992, 0.6974535 , 0.32647286, 0.73392816, 0.22013496]))

In [22]:
x = np.arange(5,10)
x[x==6]

array([6])

In [31]:
X = rng.standard_normal(size=10000)
print(f"{len(X[np.abs(X) > 1.96])/len(X):0.2%}")
print(f"{np.sum(X[np.abs(X) > 1.96])/np.sum(X):0.2%}")


5.16%
54.94%


In [72]:
# Assuming rng has been created beforehand
x = rng.normal(0, size=(3, 4))
y = np.array([np.nan, 0, 1])

print(f"Count_nonzero y: {np.count_nonzero(y)}")
print(f"Isnan y : {np.isnan(y)}")
print(x)
np.any(x>0, axis=0)

Count_nonzero y: 2
Isnan y : [ True False False]
[[-1.68285717 -1.05249749 -0.48117157 -0.40996813]
 [-1.81863474  0.94572763 -0.96525343 -0.65156547]
 [-0.25351069 -1.78815105  0.97416107 -2.89344505]]


array([False,  True,  True, False])

In [73]:
x = rng.normal(0, size=(3, 4))
print(x)

print(np.sum(x, axis=1))
print(np.sum(x, axis=0))
print(np.sum(x))

[[ 0.08563652 -0.02952754 -0.05393867 -0.87813008]
 [ 1.21920732 -1.1771456  -0.12047059  1.30195638]
 [ 0.37205295  0.25877186 -1.94933865  0.34460261]]
[-0.87595977  1.2235475  -0.97391122]
[ 1.67689679 -0.94790128 -2.12374791  0.76842891]
-0.6263234940762576
